# This rule is not used by the project kubecrds itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over webapp.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubecrds
    app.kubernetes.io/managed-by: kustomize
  name: crds-admin-role
rules:
- apiGroups:
  - webapp.example.com
  resources:
  - crds
  verbs:
  - '*'
- apiGroups:
  - webapp.example.com
  resources:
  - crds/status
  verbs:
  - get
